version: "3.3"
services:
  wakmusic-server:
    networks:
      - wakmusic-api
    container_name: server
    image: wakmusic-server:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080

networks:
  wakmusic-api:
    driver: bridge
