name: wakmusic-api
version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
      - ./../wakmusic:/home/ubuntu/wakmusic
      - ./../wakmusic-lyrics:/home/ubuntu/wakmusic-lyrics
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - wakmusic-api
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - nest-node-1
      - nest-node-2
      - nest-node-3
    links:
      - nest-node-1
      - nest-node-2
      - nest-node-3

  redis-cluster:
    networks:
      - wakmusic-api
    image: redis:latest
    container_name: redis-test
    volumes:
      - ./conf/redis/redis_6300.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6300

  redis-node-1:
    networks:
      - wakmusic-api
    image: redis:latest
    container_name: redis-test1
    volumes:
      - ./conf/redis/redis_6301.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6301

  redis-node-2:
    networks:
      - wakmusic-api
    image: redis:latest
    container_name: redis-test2
    volumes:
      - ./conf/redis/redis_6302.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6302

  redis-cluster-entry:
    networks:
      - wakmusic-api
    image: redis:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create redis-cluster:6300 redis-node-1:6301 redis-node-2:6302 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
    links:
      - redis-cluster
      - redis-node-1
      - redis-node-2

  redis-queue:
    networks:
      - wakmusic-api
    image: redis:latest
    container_name: redis-queue
    command: redis-server
    expose:
      - 6379
  
  nest-node-1:
    networks:
      - wakmusic-api
    container_name: nest-node-1
    build: 
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./../wakmusic/src:/usr/src/wakmusic/src
    expose:
      - 8080
    links:
      - redis-queue
      - redis-cluster
      - redis-node-1
      - redis-node-2

  nest-node-2:
    networks:
      - wakmusic-api
    container_name: nest-node-2
    build: 
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./../wakmusic/src:/usr/src/wakmusic/src
    expose:
      - 8080
    links:
      - redis-queue
      - redis-cluster
      - redis-node-1
      - redis-node-2

  nest-node-3:
    networks:
      - wakmusic-api
    container_name: nest-node-3
    build: 
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./../wakmusic/src:/usr/src/wakmusic/src
    expose:
      - 8080
    depends_on:
      - redis-queue
      - redis-cluster
      - redis-node-1
      - redis-node-2
    links:
      - redis-queue
      - redis-cluster
      - redis-node-1
      - redis-node-2

networks:
  wakmusic-api:
    driver: bridge